config/routes.rb
Rails.application.routes.draw do
  resources :locations, only: [:index, :new, :create, :destroy]
  root "locations#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forecast.rb
class Forecast
  attr_accessor :date, :temp_low, :temp_high, :description, :precipitation

  def initialize(date, temp_low, temp_high, description, precipitation)
    @date = date
    @temp_low = temp_low.to_i
    @temp_high = temp_high.to_i
    @description = description
    @precipitation = precipitation.to_f
  end
end

app/models/location.rb
require "resolv"

class Location < ApplicationRecord
  validates :city, :state, :zip, presence: true

  validates_format_of :zip,
                      with: /\A\d{5}\z/,
                      message: "should be in a 5 number format",
                      allow_blank: false

  validates :ip_address,
            format: {
              with: Regexp.union(Resolv::IPv4::Regex, Resolv::IPv6::Regex)
            },
            allow_blank: true

  attr_accessor :forecasts

  after_find :after_find
  before_validation :before_validation

  private

  def after_find
    if !self.zip.blank?
      self.forecasts = WeatherService.new.get_forecasts_by_zip self.zip
    end
  end

  def before_validation
    if !self.ip_address.blank?
      l = AddressService.new.get_by_ip_address(self.ip_address)
      self.address = l.address
      self.city = l.city
      self.state = l.state
      self.zip = l.zip
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
require 'net/http'
require 'json'

class LocationsController < ApplicationController
  before_action :set_location, only: %i[ destroy ]

  # GET /locations
  def index
    @locations = Location.all
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # POST /locations
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to locations_url, notice: "Location was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def location_params
    params.require(:location).permit(:address, :city, :state, :zip, :ip_address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_svg(path)
    File.open("app/assets/images/#{path}", "rb") do |file|
      raw file.read
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
  def convert_for_line_chart(forecasts)
    low_data = {}
    high_data = {}

    forecasts.each do |forecast|
      low_data[forecast.date] = forecast.temp_low.to_i
      high_data[forecast.date] = forecast.temp_high.to_i
    end

    [
      { name: "Low", data: low_data },
      { name: "High", data: high_data }
    ]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body class="bg-blue-200">
<header class="p-4 text-3xl bg-slate-800 text-white my-auto flex content-end">
  <div class="h-3 w-9">
    <%= show_svg("sun.svg") %>
  </div>
  The Weather
</header>

<main class="container mx-auto mt-10 p-5 bg-white rounded">
  <%= yield %>
</main>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location,
              data: {
                controller: "new-location"
              }) do |form| %>

  <% if location.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-4">
    <input type="checkbox"
           id="ip_entry"
           name="ip_entry"
           class="rounded"
           data-action="click->new-location#toggleIpEntry">
    <label for="ip_entry">Add by IP Address</label>
  </div>

  <div data-new-location-target="basicFields" class="space-y-3">
    <div>
      <%= form.label :address, style: "display: block" %>
      <%= form.text_field :address, class: "form-input rounded" %>
    </div>

    <div>
      <%= form.label :city, style: "display: block" %>
      <%= form.text_field :city, class: "form-input rounded" %>
    </div>

    <div>
      <%= form.label :state, style: "display: block" %>
      <%= form.text_field :state, class: "form-input rounded" %>
    </div>

    <div>
      <%= form.label :zip, style: "display: block" %>
      <%= form.text_field :zip, class: "form-input rounded" %>
    </div>
  </div>

  <div data-new-location-target="ipAddress"
       hidden>
    <%= form.label :ip_address, "IP Address", style: "display: block" %>
    <%= form.text_field :ip_address, class: "form-input rounded" %>
  </div>

  <div class="mt-4">
    <%= form.submit class: "btn-secondary" %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>" data-controller="collapsible">
  <button class="my-auto cursor-pointer hover:bg-gray-100 px-5 py-4 w-full"
          type="button"
          data-action="click->collapsible#toggle"
  >
    <span class="flex justify-between w-full">
      <span class="flex flex-col justify-start text-left text-sm sm:text-base">

        <% if !location.address.blank? %>
          <span data-test-id="address_line">
            <%= location.address %>
          </span>
        <% end %>

        <span data-test-id="city_state_zip">
          <%= location.city %>, <%= location.state %> <%= location.zip %>
        </span>

        <% if !location.ip_address.blank? %>
          <span class="text-sm italic text-gray-600 text-left" data-test-id="ip_address">
            (<%= location.ip_address %>)
          </span>
        <% end %>

      </span>

      <span class="my-auto flex">
        <span class="sm:text-2xl flex flex-col sm:block">
          <span>
            <%= location.forecasts[0].temp_low %>&deg;F /
          </span>
          <span>
            <%= location.forecasts[0].temp_high %>&deg;F
          </span>
        </span>

        <span class="w-5 h-5 sm:w-7 sm:h-7 my-auto ease-out duration-300"
              data-collapsible-target="caret">
          <%= show_svg("caret_right.svg") %>
        </span>

      </span>
    </span>
  </button>

  <div
    hidden
    class="px-5 py-4 h-full overflow-hidden"
    data-collapsible-target="content"
    data-test-id="chart"
  >
    <div>

      <h2 class="text-xl">Today's Forecast Details</h2>
      <div>
        <%= location.forecasts[0].description %>
      </div>
      <div>
        Chance of Rain: <%= (location.forecasts[0].precipitation * 100).to_i %>%
      </div>
    </div>

    <div class="mt-6">
      <h2 class="text-xl">7 Day Forecast</h2>
      <%= line_chart convert_for_line_chart location.forecasts %>
    </div>

    <div class="mt-6">
      <%= button_to "Delete", location, method: :delete, class: "btn-danger", data: { test_id: "delete" } %>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-3xl">Locations</h1>

<div id="locations" class="-mx-5 my-4">
  <% @locations.each_with_index do |location, index| %>
    <%= render location %>

    <% if index < @locations.length - 1 %>
      <hr/>
    <% end %>
  <% end %>
</div>

<%= link_to "Add location", new_location_path, class: "btn-primary" %>

app/views/locations/new.html.erb
<div class="mb-4">
  <%= link_to locations_path,
              class: "link flex" do %>

    <div class="rotate-180 h-6 w-6 my-auto">
      <%= show_svg("caret_right.svg") %>
    </div>
    Back
  <% end %>
</div>

<h1 class="text-3xl mb-4">New Location</h1>

<%= render "form", location: @location %>